# Generated by Django 4.2.16 on 2024-11-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barakaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=255, null=True)),
                ('farmer_number', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('sales', 'Sales'), ('accounts', 'Accounts'), ('hybrid', 'Hybrid')], default='sales', max_length=20),
        ),
    ]
