# Generated by Django 4.2.16 on 2024-11-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barakaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
