# Generated by Django 4.2.16 on 2024-11-12 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barakaApp', '0002_farmer_alter_useraccount_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Milled',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('farmer_name', models.CharField(max_length=255)),
                ('kgs', models.CharField(max_length=255)),
                ('output', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('refferal', models.CharField(max_length=255, null=True)),
                ('mill_date', models.DateField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('farmer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barakaApp.farmer')),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barakaApp.machine')),
            ],
        ),
    ]
