# Generated by Django 4.2.16 on 2024-11-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barakaApp', '0002_alter_farmer_alias_alter_farmer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milled',
            name='refferal',
        ),
        migrations.AddField(
            model_name='farmer',
            name='refferal',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
