# Generated by Django 4.2.1 on 2024-12-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barakaApp', '0004_farmer_secondary_phone_alter_payments_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_mode',
            field=models.CharField(choices=[(1, 'Cash'), (2, 'Mpesa'), (3, 'Bank'), (4, 'KCB'), (5, 'Equity'), (6, 'Almanis Tier A'), (7, 'Almanis Tier B')], max_length=255),
        ),
    ]
