# Generated by Django 4.2.1 on 2024-12-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barakaApp', '0005_alter_payments_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='amount',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
