# Generated by Django 4.2.1 on 2024-12-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barakaApp', '0008_payments_kilos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='phone',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='secondary_phone',
            field=models.CharField(default=0, max_length=255, null=True, unique=True),
        ),
    ]
