# Generated by Django 4.2.16 on 2025-01-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barakaApp', '0012_alter_farmer_alias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='kilos',
            new_name='receipt_number',
        ),
    ]
