# Generated by Django 4.2.16 on 2025-01-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barakaApp', '0013_rename_kilos_payments_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='kilos',
            field=models.CharField(choices=[(1, 'Cash'), (2, 'Mpesa'), (3, 'KCB'), (4, 'Equity'), (5, 'Almanis Tier A'), (6, 'Almanis Tier B'), (7, 'Others')], default=0, max_length=255),
        ),
    ]
