# Generated by Django 4.2.1 on 2025-01-21 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barakaApp', '0016_remove_milled_farmer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='price',
            field=models.CharField(default=2.5, max_length=255),
        ),
    ]
