# Generated by Django 4.2.16 on 2026-04-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barakaApp', '0017_payments_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='secondary_phone',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
