# Generated by Django 4.2.16 on 2026-04-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barakaApp', '0018_alter_farmer_secondary_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='farmer_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='refferal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='secondary_phone',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
